version: '3.7'
services:
  db:
    image: ${DATABASE_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME}-db
    ports:
      - "${DATABASE_PORT:-3306}:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_HOST=${COMPOSE_PROJECT_NAME}-db
      - MYSQL_ROOT_PASSWORD=${COMPOSE_PROJECT_NAME}1234
      - MYSQL_DATABASE=${COMPOSE_PROJECT_NAME}
      - MYSQL_USER=${COMPOSE_PROJECT_NAME}
      - MYSQL_PASSWORD=${COMPOSE_PROJECT_NAME}1234
    networks:
      - backend

volumes:
  dbdata:
    name: ${COMPOSE_PROJECT_NAME}-dbdata

networks:
  backend:
    name: backend
