version: '3.7'

services:
  db:
    hostname: db.magento2.docker
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: '${DATABASE_IMAGE}'
    shm_size: 2gb
    environment:
      - MYSQL_ROOT_PASSWORD=${COMPOSE_PROJECT_NAME}1234
      - MYSQL_DATABASE=${COMPOSE_PROJECT_NAME}
      - MYSQL_USER=${COMPOSE_PROJECT_NAME}
      - MYSQL_PASSWORD=${COMPOSE_PROJECT_NAME}1234
    ports:
      - "${DATABASE_PORT:-3306}:3306"
    volumes:
      - 'magento-db:/var/lib/mysql'
    healthcheck:
      test: 'mysqladmin ping -h localhost -p${COMPOSE_PROJECT_NAME}1234'
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:
        aliases:
          - db.magento2.docker

  redis:
    hostname: redis.magento2.docker
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: '${REDIS_IMAGE}'
    ports:
      - "${REDIS_PORT:-6379}:6379"
    sysctls:
      net.core.somaxconn: 1024
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:
        aliases:
          - redis.magento2.docker

  elasticsearch:
    hostname: elasticsearch.magento2.docker
    container_name: ${COMPOSE_PROJECT_NAME}-elasticsearch
    image: '${ELASTICSEARCH_IMAGE}'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"
    networks:
      magento:
        aliases:
          - elasticsearch.magento2.docker

  rabbitmq:
    hostname: rabbitmq.magento2.docker
    container_name: ${COMPOSE_PROJECT_NAME}-rabbitmq
    image: '${RABBITMQ_IMAGE}'
    ports:
      - "${RABBITMQ_PORT:-15672}:15672"
      - "${RABBITMQ_WEB_PORT:-5672}:5672"
    networks:
      magento:
        aliases:
          - rabbitmq.magento2.docker

volumes:
  magento-db:
    name: ${COMPOSE_PROJECT_NAME}-magento-db

networks:
  magento:
    driver: bridge
